#!/bin/sh
set -eu
ARCH=$(uname -m)

echo "Installing package dependencies..."
echo "---------------------------------------------------------------"
pacman -Syu --noconfirm \
    cmake    \
    libdecor \
    sdl3

echo "Installing debloated packages..."
echo "---------------------------------------------------------------"
get-debloated-pkgs --add-common --prefer-nano

echo "Making lba2 classic community..."
echo "---------------------------------------------------------------"
cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

# Pull product metadata generated by CMake (LBA2_PRODUCT_NAME,
# LBA2_EXECUTABLE_NAME, LBA2_DESKTOP_ID). Single source of truth lives in
# the LBA2_* cache variables in the root CMakeLists.txt; override with -D.
. ./build/packaging/appimage_env.sh

cmake --build build --target "${LBA2_EXECUTABLE_NAME}"

# Copy the version file to dist directory
mkdir -p ./dist
cp build/VERSION.txt ./dist/VERSION.txt

mkdir -p ./AppDir/bin
cp -v ./packaging/"${LBA2_DESKTOP_ID}.png" ./AppDir/
cp -v ./build/packaging/"${LBA2_DESKTOP_ID}.desktop" ./AppDir/

read -r VERSION < ./dist/VERSION.txt
export ARCH VERSION
export OUTPATH=./dist
export ADD_HOOKS="self-updater.hook"
export UPINFO="gh-releases-zsync|${GITHUB_REPOSITORY%/*}|${GITHUB_REPOSITORY#*/}|latest|*$ARCH.AppImage.zsync"
export APPNAME="${LBA2_PRODUCT_NAME}"
export DEPLOY_OPENGL=1

quick-sharun "./build/SOURCES/${LBA2_EXECUTABLE_NAME}"
quick-sharun --make-appimage
