#!/usr/bin/env bash
# Local dry-run for the Windows release artifact.
#
# Cross-compiles via the cross_linux2win preset (32-bit i686 currently —
# the toolchain available on Linux dev boxes), statically linked, then
# bundles into the same ZIP shape the eventual CI release workflow will
# produce. Lets you iterate on packaging (ZIP layout, README content,
# static-link audit) without burning GitHub minutes.
#
# Outputs: dist/lba2cc-<version>-windows-i686.zip
#
# Requires: i686-w64-mingw32-gcc (apt: mingw-w64), cmake, ninja, zip.
#
# The CI release workflow uses native MSYS2 UCRT64 to produce x64
# artifacts; this script and that workflow share scripts/packaging/
# bundle-windows.sh so the ZIP layout can't drift between them.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"
cd "$REPO_ROOT"

BUILD_DIR="${LBA2_BUILD_DIR:-out/build/cross_linux2win}"
OUTPUT_DIR="${LBA2_DIST_DIR:-dist}"
ARCH="i686"   # determined by the cross_linux2win toolchain file

# Sanity: cross-compile toolchain present.
if ! command -v i686-w64-mingw32-gcc >/dev/null 2>&1; then
    echo "i686-w64-mingw32-gcc not found." >&2
    echo "Install with: sudo apt install mingw-w64    (Ubuntu/Debian)" >&2
    echo "         or:  sudo pacman -S mingw-w64-gcc  (Arch)" >&2
    exit 1
fi

echo "[build-windows-release] preset:    cross_linux2win"
echo "[build-windows-release] static:    LBA2_LINK_STATIC=ON"
echo "[build-windows-release] build dir: $BUILD_DIR"
echo "[build-windows-release] output:    $OUTPUT_DIR"

# Configure + build. Override LBA2_LINK_STATIC=ON via cache override —
# the preset stays unchanged so it remains a fast iteration target for
# anyone who just wants to confirm Windows builds.
cmake --preset cross_linux2win -DLBA2_LINK_STATIC=ON
cmake --build --preset cross_linux2win

# Resolve the executable name from the cache (follows any
# -DLBA2_EXECUTABLE_NAME override).
EXE_NAME=$(awk -F= '/^LBA2_EXECUTABLE_NAME:[^=]+=/{print $2; exit}' \
    "$BUILD_DIR/CMakeCache.txt")
EXE_NAME="${EXE_NAME:-lba2cc}"
EXE_PATH="$BUILD_DIR/SOURCES/${EXE_NAME}.exe"

if [[ ! -f "$EXE_PATH" ]]; then
    echo "[build-windows-release] expected $EXE_PATH but it doesn't exist" >&2
    exit 1
fi

# Read version (already generated by the build into VERSION.txt).
VERSION=$(< "$BUILD_DIR/VERSION.txt")

mkdir -p "$OUTPUT_DIR"

bash "$REPO_ROOT/scripts/packaging/bundle-windows.sh" \
    --exe "$EXE_PATH" \
    --version "$VERSION" \
    --arch "$ARCH" \
    --build-dir "$BUILD_DIR" \
    --output-dir "$OUTPUT_DIR"
