name: Release Linux AppImage

on:
  push:
    tags:
      - 'v*' # Triggers only on version tags
  workflow_dispatch:

jobs:
  build:
    name: "Build ${{ matrix.arch }}"
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-latest
            arch: x86_64
          - runs-on: ubuntu-24.04-arm
            arch: aarch64
    container: ghcr.io/pkgforge-dev/archlinux:latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      # Get the version on the HOST (outside the container)
      - name: Get version
        id: get_version
        run: echo "VERSION=$(git rev-parse --short=9 HEAD)" >> $GITHUB_ENV
      - name: Preparing Container
        uses: pkgforge-dev/anylinux-setup-action@v2
      - name: Install Dependencies
        run: pacman -Syu --noconfirm sdl3 cmake ninja
      - name: Build and Make AppImage
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target lba2

          # Desktop entry
          mkdir -p ./AppDir
          cat > ./AppDir/lba2.desktop <<EOF
          [Desktop Entry]
          Type=Application
          Name=LBA2 Classic Community
          Comment="A community fork for evolving and modernizing LBA2 source port"
          Exec=lba2
          Icon=lba2
          StartupWMClass=lba2
          Categories=Game;Adventure;Platform;
          X-AppImage-Version=$VERSION
          EOF

          # Metadata for Release Action
          echo "X-AppImage-Name=lba2-classic-community" > ./appinfo
          echo "X-AppImage-Version=$VERSION" >> ./appinfo
          
          # quick-sharun
          wget "https://raw.githubusercontent.com/pkgforge-dev/Anylinux-AppImages/refs/heads/main/useful-tools/quick-sharun.sh" -O ./quick-sharun
          chmod +x ./quick-sharun
          
          export ARCH=${{ matrix.arch }}
          export OUTPATH=./dist
          export ADD_HOOKS="self-updater.hook"
          export UPINFO="gh-releases-zsync|${{ github.repository_owner }}|${{ github.event.repository.name }}|latest|*$ARCH.AppImage.zsync"
          
          ./quick-sharun ./build/SOURCES/lba2
          ./quick-sharun --make-appimage

      - name: Upload temporary artifact
        uses: actions/upload-artifact@v4
        with:
          name: AppImage-${{ matrix.arch }}
          path: dist
          
   release:
    needs: [build]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: AppImage-*
          merge-multiple: true
      - name: Generate appinfo for release
        run: |
          VERSION=$(git rev-parse --short=9 HEAD)
          echo "X-AppImage-Name=lba2-classic-community" > ./appinfo
          echo "X-AppImage-Version=$VERSION" >> ./appinfo
      - name: Release AppImage
        uses: pkgforge-dev/make-stable-appimage-release@v1.1
